### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by danielklk** [ahmedrangel/instagram-media-scraper#1]
Which cookie information I use?

sessionid= mid= ig_nrcb= ig_did ds_user_id= csrftoken= whic one I use for the _cookie = ?

2 errors

![Screenshot 2023-07-14 034641](https://github.com/ahmedrangel/instagram-media-scraper/assets/102783850/545edba6-bdec-4aa6-bfb7-0adb92ac572b)
![Screenshot 2023-07-14 034630](https://github.com/ahmedrangel/instagram-media-scraper/assets/102783850/198839ae-666c-4677-bd6f-4d9dfc5738c3)

**Comment by ahmedrangel** [comment]
> Which cookie information I use?
> 
> sessionid= mid= ig_nrcb= ig_did ds_user_id= csrftoken= whic one I use for the _cookie = ?
> 
> 2 errors
> 
> ![Screenshot 2023-07-14 034641](https://user-images.githubusercontent.com/102783850/253494124-545edba6-bdec-4aa6-bfb7-0adb92ac572b.jpg) ![Screenshot 2023-07-14 034630](https://user-images.githubusercontent.com/102783850/253494128-198839ae-666c-4677-bd6f-4d9dfc5738c3.jpg)

For _cookie you must use all of them declared as a single string.

And these errors are probably a Node version incompatibility when running the code. Are you using Node to run it? If so, make sure your Node version is at least v18.16.
