### ISSUE TITLE
Help with fbm_...;  fbsr_=...

### ISSUE THREAD

**Issue by danielklk** [ahmedrangel/instagram-media-scraper#2]
I couldn't find these values inside the cookie.

**Comment by ahmedrangel** [comment]
> I couldn't find these values inside the cookie.

Sometimes not all of the cookie values are there, I think it depends on the browser, just copy all the ones that appear to you and you should be able to get the data

**Comment by danielklk** [comment]
How many URLs can you scrape before Instagram logout the account?

**Comment by danielklk** [comment]
Can you access the videos posts? The videos URLs are inside a string, and there are more than one URL by post. But when I try to open the URLs, I receive a message inside instagram webpage, even not connected: "URL signature expired"

**Comment by ahmedrangel** [comment]
I don't know how long it takes for instagram to log out of the account, as my experience it takes something about a little more than 1 month but sometimes about 2 weeks, after that I have to renew the cookie I'm using.

It is normal that there are several urls per post but it is weird that you cannot open them, currently I can open them without problem.
