### ISSUE TITLE
Account Suspended 

### ISSUE THREAD

**Issue by Arish68** [ahmedrangel/instagram-media-scraper#3]
My Instagram account was suspended after only 3 days, with just 5 strikes. Could you please share a solution for this issue?

**Comment by ahmedrangel** [comment]
I'm so sorry about that, I've been using this method since June and haven't received any suspensions or restrictions so for now I have no idea how to fix it. I don't know what could cause it besides making bulk requests.

**Comment by Arish68** [comment]
@ahmedrangel kindly share your live site or app where you did integrate this code
